version: '3'

services:
  puppeteer:
    build: .
    depends_on:
      - redis
    links:
      - redis
    # Environment variables to configure the connection to Redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # Uncomment if you need to expose a port from your Puppeteer script
    # ports:
    #   - "3000:3000"

  redis:
    image: redis

  # redis-api:
  #   image: gkorland/redix
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
